### ISSUE TITLE
Code testing related issues

### ISSUE THREAD

**Issue by nr45478** [JingyiXu404/TPAMI-DeepM2CDL#2]
Hello, may I ask if there are matching problems of multiple scales in the running process of your code, including the mismatch of X, Y and D dimensions? Have you ever encountered this problem? Hope to get your answer.

**Comment by JingyiXu404** [comment]
We achieve multi-scale by setting the dictionary filter D to different sizes (e.g. d_size = 3×3, 5×5). The dimension of D matches X and Y. To deal with a mismatch, you can modify the initialization step of 'self.head_d' in 'class HeadNet'.

**Comment by nr45478** [comment]
I solved it by reconfiguring the torch version, thanks!
